stages:
  - test

.test_template: &test_definiton |
  export JULIA_PROJECT=@.
  export JL_PKG=ROOTIO
  export JULIA_NUM_THREADS=3
  julia --check-bounds=yes --color=yes -e "using Pkg; Pkg.test(coverage=true)"

test-julia-1.3:
  image: julia:1.3
  script:
    - *test_definiton

test-julia-1.6:
  image: julia:1.6
  script:
    - *test_definiton
