name: Test C++ ROOT read back
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags: '*'
jobs:
  test:
    name: C++ ROOT read back rntuple files ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04]
        arch: [x64]
        allow_failure: [false]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - name: Generate root file
        run: |
          julia --code-coverage --project ./test/RNTupleWriting/output_sample.jl test1.root
      - uses: cvmfs-contrib/github-action-cvmfs@v4
      - name: Read root file in C++
        run: |
          source /cvmfs/sft.cern.ch/lcg/views/dev3/latest/x86_64-ubuntu2204-gcc11-opt/setup.sh
          python ./test/RNTupleWriting/test1.py test1.root
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: lcov.info
