name: Downgrade
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
jobs:
  test:
    name: "Downgrade Julia compats test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['lts']
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: julia-actions/setup-julia@fa02766e078afaaf09b14210362cee14137e6a32 # v3.0.2
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/julia-downgrade-compat@00f940b7be2b50389571ed016d603be561649103 # v2.2.2
        with:
          skip: Pkg,TOML,Mmap,Test,Random,InteractiveUtils
      - uses: julia-actions/julia-buildpkg@e3eb439fad4f9aba7da2667e7510e4a46ebc46e1 # v1.7.0
      - uses: julia-actions/julia-runtest@d60b785c6f2bdf4ebfb18b2b6f7d93b7dfb0efe3 # v1.11.4
